# .github/workflows/compose-build-push.yml
name: Build, Push and Deploy with Compose

on:
  push:
    branches: [ "master" ]
  

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: olegsirik/papi-b
  FRONTEND_IMAGE: olegsirik/papi-f

jobs:
  build-and-test: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test with Docker Compose
        run: |
          # Собираем образы
          docker compose --env-file docker-compose.env -f docker-compose.env build

          echo "=== Built images ==="
          docker compose images
          
          # Запускаем сервисы
          docker compose --env-file docker-compose.env -f docker-compose.yml up -d
          
          # Ждем готовности
          sleep 30
        
          
          # Проверяем здоровье сервисов
          # curl -f http://localhost:80/health || exit 1
          # curl -f http://localhost:8080/health || exit 1

      - name: Push images to Docker Hub
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Тегируем и пушим backend
          docker tag papi-b:latest ${{ env.BACKEND_IMAGE }}:latest
          #docker tag backend:latest ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.BACKEND_IMAGE }}:latest 
          #docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          
          # Тегируем и пушим frontend
          docker tag papi-f:latest ${{ env.FRONTEND_IMAGE }}:latest
          #docker tag frontend:latest ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.FRONTEND_IMAGE }}:latest
          #docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: |
          docker compose --env-file docker-compose.env down
          docker system prune -f

  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |          
            # Pull latest code
            cd PtDocker
            git pull origin master
            echo "Текущий статус репозитория:"
            git status
            
            # Deploy
            docker compose down
            docker compose --env-file docker-compose.env up -d --build
            
            
              
