# .github/workflows/compose-build-push.yml
name: Build, Push and Deploy with Compose

on:
  push:
    branches: [ "master" ]
  

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: olegsirik/myapp-backend
  FRONTEND_IMAGE: olegsirik/myapp-frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: olegsirik
          password: dckr_pat_4TRi4iZNO9x6MquIFlPUGd2HLUk

      - name: Build and test with Docker Compose
        run: |
          # Собираем образы
          docker compose -f docker-compose-mac-local.yml build
          
          # Запускаем сервисы
          docker compose -f docker-compose-mac-local.yml up -d
          
          # Ждем готовности
          sleep 30
        
          
          # Проверяем здоровье сервисов
          # curl -f http://localhost:80/health || exit 1
          # curl -f http://localhost:8080/health || exit 1

      - name: Push images to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Тегируем и пушим backend
          docker tag myapp-backend:latest ${{ env.BACKEND_IMAGE }}:latest
          docker tag myapp-backend:latest ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          
          # Тегируем и пушим frontend
          docker tag myapp-frontend:latest ${{ env.FRONTEND_IMAGE }}:latest
          docker tag myapp-frontend:latest ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          docker push ${{ env.FRONTEND_IMAGE }}:latest
          docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose-mac-local.yml down
          docker system prune -f
